name: Deploy Sisag

on:
  push:
    branches:
      - main
      - master

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Login no GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build da imagem Next.js (standalone)
        run: |
          docker build -t ghcr.io/flaience/sisag:latest .

      - name: Push da imagem
        run: |
          docker push ghcr.io/flaience/sisag:latest

      - name: Deploy no servidor via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/flaience/sisag:latest
            docker service update --force \
              --image ghcr.io/flaience/sisag:latest \
              sisag_app-frontend
